# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  tfss_config = debug

else ifeq ($(config),release)
  tfss_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := tfss

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

tfss:
ifneq (,$(tfss_config))
	@echo "==== Building tfss ($(tfss_config)) ===="
	@${MAKE} --no-print-directory -C . -f tfss.make config=$(tfss_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f tfss.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tfss"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"